baseURL = 'https://ink-kai.github.io/'
disableKinds = true
languageCode = 'zh-cn'
theme = "InkCat"
title = 'InkCat博客'
# GA分析统计
googleAnalytics = "GA ID"
[markup]
[markup.highlight]
lineNos = true
style = "github"
[menu]
[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 2
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 3
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 4
# 图片cdn
[Params.image_cdn]
Host = "https://cdn.jsdelivr.net/gh/user/user.github.io"
enable = true
[Author]
name = "InkCat"
[Params]
date = "2022/05/20"
fancybox = true
localSearch = true
subtitle = "要么活,要么死"
# 开启目录
toc = true
# 默认：cdnjs.cloudflare.com
cdnJsSite = "cdn.bootcdn.net"
# 支持Disqus评论
disqusShortname = "InkCat"
# 知识版权
[Params.cc]
link = "http://www.bjdcmm.org.cn/node/1494"
name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
## 配置 utteranc评论,教程参考 https://utteranc.es/
[Params.utteranc]
enable = false 
issueTerm = "title" 
repo = "Ink-kai/Ink-kai.github.io/" ##换成自己得
theme = "github-light"
