baseURL = 'https://ink-kai.github.io/'
languageCode = 'zh-cn'
summaryLength = 140
theme = "blogtheme"
title = 'InkCat博客'
# GA分析统计
googleAnalytics = "GA ID"
[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
tabWidth = 4
# 样式参考：https://xyproto.github.io/splash/docs/all.html
style = "monokai"
[menu]
[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 2
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 3
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 4
# 图片cdn
[Params.image_cdn]
Host = "https://cdn.jsdelivr.net/gh/Ink-kai/Ink-kai.github.io"
enable = true
[Params]
busuanzi = true
date = "2022/05/20"
# 图片点击放大
fancybox = true
# 本地搜索
localSearch = true
# 副标题
subtitle = "要么活,要么死"
# 开启目录
toc = true
# 默认：cdnjs.cloudflare.com
cdnJsSite = "cdn.bootcdn.net"
customCSS = ["copy-to-clipboard.css"]
customJS = ['copy-to-clipboard.js', "hrefblank.js"]
# 知识版权
[Params.cc]
link = "http://www.bjdcmm.org.cn/node/1494"
name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
## 配置 utteranc评论,教程参考 https://utteranc.es/
[Params.utteranc]
enable = true 
issueTerm = "title" 
repo = "Ink-kai/Ink-kai.github.io" ##换成自己得
theme = "github-light"